_wandb:
    value:
        cli_version: 0.19.5
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 1
                - 16
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.5
            "6": 4.48.2
            "8":
                - 3
                - 5
            "12": 0.19.5
            "13": windows-amd64
hidden_dim:
    value: 64
input_dim:
    value: 768
l1_coefficient:
    value: 0.001
learning_rate:
    value: 0.001
model_type:
    value: SparseAutoencoder
